### ISSUE TITLE
AA duplicates

### ISSUE THREAD

**Issue by shady7x** [Oldsalt0/SpellReplay#2]
Consider using spell ids instead of hardcoded spell names because it wont work if ur client is not in english, for example id 75 instead of autoshot and so on, otherwise it will show autoshot twice, first one being without damage

**Comment by Oldsalt0** [comment]
Hey @shady7x, thanks for testing my addon.
Sadly I did not touch it since quite some time, given that the former TBC community turned out to be disappointing and that I am not interested in Blizzard official servers.

I'm not using the spell name to display the melee/ranged auto attacks, as you can see [line 2000](https://github.com/Oldsalt0/SpellReplay/blob/8dc43ba2ebe58a132494d6dbc193ed5961e0702a/SpellReplay.lua#L2000). However I was indeed using hardcoded names to avoid that second display you mention, at [line 1674](https://github.com/Oldsalt0/SpellReplay/blob/8dc43ba2ebe58a132494d6dbc193ed5961e0702a/SpellReplay.lua#L1674).
Feel free to modify that line by using the first return of GetSpellInfo(spellID) for each of the occurences, or at least those which matter for you.
